# Generated by Django 2.1.4 on 2021-08-05 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RushingStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=5)),
                ('pos', models.CharField(max_length=5)),
                ('att', models.IntegerField()),
                ('att_g', models.FloatField()),
                ('yds', models.IntegerField()),
                ('avg', models.FloatField()),
                ('yds_g', models.FloatField()),
                ('td', models.IntegerField()),
                ('lng', models.IntegerField()),
                ('first', models.IntegerField()),
                ('first_percentage', models.FloatField()),
                ('twenty_plus', models.IntegerField()),
                ('forty_plus', models.IntegerField()),
                ('fum', models.IntegerField()),
            ],
        ),
    ]
